#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=environment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:10:00
#SBATCH --output=outputs/environment_%j.out

# Load necessary modules
module purge
module load 2024
module load Anaconda3/2024.06-1
# Load CUDA after Anaconda3 and before activating conda env
module load CUDA/12.0.0 

# Activate the Conda environment
source activate erwin

# Actual script
conda env update --file environment.yml --prune