name: erwin
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pytorch=2.5.0
  - pip
  - wheel
  - addict
  - cython
  - einops
  - h5py
  - numpy
  - pandas
  - setuptools
  - tensorflow
  - matplotlib
  - tqdm
  - timm
  - wandb
  - pip:
    - gatr @ git+https://github.com/Qualcomm-AI-research/geometric-algebra-transformer.git