name: erwin
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pip
  - wheel
  - addict
  - cython
  - einops
  - h5py
  - numpy
  - pandas
  - setuptools
  - tensorflow
  - matplotlib
  - tqdm
  - timm
  - wandb
  - pip:
    - torch==2.4.1 -f https://data.pyg.org/whl/torch-2.4.1+cu120.html
    - gatr @ git+https://github.com/Qualcomm-AI-research/geometric-algebra-transformer.git --find-links https://data.pyg.org/whl/torch-2.4.1+cu120.html
    - torch-scatter
    - spconv-cu120
    - torch-cluster -f https://data.pyg.org/whl/torch-2.4.1+cu120.html
    - xformers==0.0.28.post1